# Generated by Django 4.2.23 on 2025-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='leader',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
