# Generated by Django 4.2.23 on 2025-08-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0002_alter_departmentmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'ordering': ['order', 'id'], 'verbose_name': '部门', 'verbose_name_plural': '部门管理'},
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='部门名称'),
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_department_name_per_parent', violation_error_message='同级部门下已存在相同名称的部门'),
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_department_code', violation_error_message='部门编码必须唯一'),
        ),
    ]
