# Generated by Django 4.2.23 on 2025-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0003_alter_departmentmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentmodel',
            name='unique_department_name_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='departmentmodel',
            name='unique_department_code',
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='code',
            field=models.CharField(error_messages={'unique': '部门编码必须唯一'}, max_length=20, unique=True, verbose_name='部门编码'),
        ),
    ]
