# Generated by Django 4.2.23 on 2025-08-15 08:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionmodel',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='permissionmodel',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='rolepermissionmodel',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='userrolemodel',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='权限标识')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=128, null=True, verbose_name='组件路径')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('type', models.IntegerField(choices=[(0, '目录'), (1, '菜单'), (2, '按钮')], default=0, verbose_name='类型')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authSystem.menumodel', verbose_name='父菜单')),
            ],
            options={
                'db_table': 'system_menu',
                'ordering': ['order'],
            },
        ),
    ]
