# Generated by Django 4.2.23 on 2025-08-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0003_rolemenumodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemenumodel',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='rolemenumodel',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='rolepermissionmodel',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='rolepermissionmodel',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userrolemodel',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userrolemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
