# Generated by Django 4.2.23 on 2025-08-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0004_rename_menu_id_rolemenumodel_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色编码'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色名称'),
        ),
    ]
