# Generated by Django 4.2.23 on 2025-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0009_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
