# Generated by Django 4.2.23 on 2025-10-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='权限标识')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=128, null=True, verbose_name='组件路径')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('type',
                 models.IntegerField(choices=[(0, '目录'), (1, '菜单'), (2, '按钮')], default=0, verbose_name='类型')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='children', to='oauth.menumodel', verbose_name='父菜单')),
            ],
            options={
                'db_table': 'system_menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='权限ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限描述')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='角色编码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('description', models.TextField(verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('account', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('avatar',
                 models.ImageField(default='avatars/0001/01/01/default.png', null=True, upload_to='avatars/%Y/%m/%d/',
                                   verbose_name='头像')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('description', models.TextField(verbose_name='个人简介')),
                ('signature', models.TextField(verbose_name='个性签名')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.rolemodel',
                                           verbose_name='角色ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.usermodel',
                                           verbose_name='用户ID')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色-权限ID')),
                ('permission',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.permissionmodel',
                                   verbose_name='权限ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.rolemodel',
                                           verbose_name='角色ID')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色-菜单ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.menumodel',
                                           verbose_name='菜单ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.rolemodel',
                                           verbose_name='角色ID')),
            ],
            options={
                'db_table': 'role_menu',
            },
        ),
    ]
