# Generated by Django 4.2.23 on 2025-08-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='权限ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('code', models.CharField(max_length=32, verbose_name='角色编码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('description', models.TextField(verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('account', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='头像')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('description', models.TextField(verbose_name='个人简介')),
                ('signature', models.TextField(verbose_name='个性签名')),
                ('last_login_time', models.DateTimeField(verbose_name='上次登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.rolemodel',
                                              verbose_name='角色ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.usermodel',
                                              verbose_name='用户ID')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色-权限ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.permissionmodel',
                                   verbose_name='权限ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.rolemodel',
                                              verbose_name='角色ID')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
    ]
