# Generated by Django 4.2.23 on 2025-08-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_rename_created_at_permissionmodel_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色-菜单ID')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.menumodel',
                                              verbose_name='菜单ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.rolemodel',
                                              verbose_name='角色ID')),
            ],
            options={
                'db_table': 'role_menu',
            },
        ),
    ]
