# Generated by Django 4.2.23 on 2025-08-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_alter_rolemodel_code_alter_rolemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children', to='oauth.menumodel', verbose_name='父菜单'),
        ),
    ]
