# Generated by Django 4.2.23 on 2025-08-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_alter_menumodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
