# Generated by Django 4.2.23 on 2025-08-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authSystem', '0006_alter_menumodel_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门编码')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('leader', models.CharField(blank=True, max_length=20, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='adminServer.departmentmodel', verbose_name='上级部门')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主部门')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='adminServer.departmentmodel', verbose_name='部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_relations', to='authSystem.usermodel', verbose_name='用户')),
            ],
            options={
                'db_table': 'user_department',
                'unique_together': {('user', 'department')},
            },
        ),
    ]
