# Generated by Django 4.2.23 on 2025-08-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0008_alter_usermodel_phone'),
        ('adminServer', '0004_remove_departmentmodel_unique_department_name_per_parent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDepartment',
            new_name='UserDepartmentModel',
        ),
    ]
